artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/shivani983/skincare-recommendation-system/main/notebook/cosmetics.zip

  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data



data_validation_config:
  cosmetics_csv_file: "cosmetics.csv"
  clean_data_dir: "clean_data"
  serialized_objects_dir: "serialized_objects"


data_transformation_config:
  transformed_data_dir: transformed_data

model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: knn_model.pkl

get_recommendation_config:
  recommendation_dir: recommendation
  product_df_serialized_objects: recommendation/artifacts/product_df.pkl
  vectorizer_serialized_objects: recommendation/artifacts/vectorizer.pkl
  cosine_similarity_serialized_objects: recommendation/artifacts/cosine_similarity.pkl



  